[alias]
ops = "run  --package habi2ca-ops --bin habi2ca-ops"
backend = "ops backend"
frontend = "ops frontend"
docker = "ops docker"
t = "ops test"
migrate = "run --bin migrate --features=tokio --"
o = "ops"
b = "backend"
f = "frontend"
