[alias]
t = "nextest run"
ops = "run --bin habi2ca-ops"
backend = "ops backend"
frontend = "ops frontend"
docker = "ops docker"
migrate = "run --bin migrate --features=tokio --"
o = "ops"
b = "backend"
f = "frontend"