[package]
name = "habi2ca-frontend"
version = "0.0.0"
edition = "2021"

[dependencies]
habi2ca-common = { version = "0.0.0", path = "../habi2ca-common" }
iced = "0.12.1"
reqwest = { version = "0.12.5", features = ["blocking", "json"] }
serde_json.workspace = true
