---
name: CD
on:       # yamllint disable-line rule:truthy
    push:
        branches:
            - main
            - ci-test

jobs:
    ci:
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository
              uses: actions/checkout@v4

            - name: Authenticate with Google Cloud
              uses: google-github-actions/auth@v2
              with:
                  project_id: habi2ca-429416
                  credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

            - name: Set up Cloud SDK
              uses: google-github-actions/setup-gcloud@v2

            - name: Build and submit
              run: gcloud builds submit
